server.port: 8080

spring:
  application:
    name: api-getaway
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    note-service:
#      service-id: note-service
